#' @title get_why_stopped
#' 
#' @description This function retrieves the reason for trial
#'     termination, if given, for a specified clinical trial.
#'
#' @param nctid A character string or a vector of character strings
#'     containing a trial registration number for ClinicalTrials.gov.
#'
#' @param historical_version A Boolean TRUE or FALSE. If TRUE, the
#'     function expects a data frame containing historical version
#'     data of the type generated by
#'     `cthist::clinicaltrials_gov_download()`. If FALSE, this
#'     function will download the historical version data. FALSE by
#'     default.
#'
#' @param df A data frame containing historical version data of the
#'     type generated by `cthist::clinicaltrials_gov_download()`, will
#'     be used instead of downloading new data if argument
#'     `historical_version` is TRUE, and if FALSE, ignored.
#'
#' @return A data frame with two columns: `nctid`, which contains
#'     ClinicalTrials.gov trial registration numbers and
#'     `reason_for_termination`, which will contain the reason why the
#'     trial was stopped, if provided. If the reason is not available,
#'     `reason_for_termination` will contain "[No reason posted]".
#'
#' @export
#'
#' @examples 
#'
#' get_why_stopped("NCT00480077")
#' ## Low enrollment rates
#'
#' get_why_stopped(c("NCT04007003", "NCT03693833", "NCT04338971"))
#' ## Sponsor decision, COVID-19 and [No reason posted]

get_why_stopped <- function(
                            nctid,
                            historical_version = FALSE,
                            df = NULL
                            ) {
    
    ## Ensure nctid is character or a vector of characters
    assertthat::assert_that(
                    is.character(nctid) |
                    (is.vector(nctid) && is.character(nctid)),
                    all(grepl("^NCT\\d{8}$", nctid)),
                    msg=paste(
                        "The argument `nctid` must be a character",
                        "string or vector of character strings"
                    )
                )

    ## Argument historical_version must be TRUE or FALSE
    assertthat::assert_that(
                    historical_version == TRUE |
                    historical_version == FALSE,
                    msg=paste(
                        "The argument `historical_version` must be",
                        "TRUE or FALSE"
                    )
                )

    if (! historical_version) {
        ## Retrieve historical version of nct_ids
        raw_trials <- cthist::clinicaltrials_gov_download(nctid)
    } else {
        ## If If historical version is TRUE, use the provided data
        assertthat::assert_that(
                        ! is.null(df),
                        msg=paste(
                            "When historical_version is TRUE,",
                            "the argument df cannot be NULL"
                        )
                    )        
        ## If df is provided, use it  
        raw_trials <- df
    }
    
    ## Create reason for termination variable (refers to the reason of
    ## termination for a clinical trial)
    get_why_stopped_df <- raw_trials |> 
        dplyr::group_by(nctid) |> 
        dplyr::mutate(
                   reason_for_termination =
                       ifelse(
                           any(nzchar(whystopped)),
                           dplyr::last(na.omit(whystopped)),
                           NA_character_
                       )
               ) |> 
        dplyr::ungroup()
    
    ## Group by nct_id and mutate reason for trial termination
    get_why_stopped_df <- get_why_stopped_df |>
        dplyr::group_by(nctid) |>
        dplyr::mutate(
                   reason_for_termination =
                       ifelse(
                           is.na(reason_for_termination),
                           "[No reason posted]",
                           reason_for_termination
                       )
               ) |>
        dplyr::distinct(nctid, .keep_all=TRUE) |>
        dplyr::ungroup() |>
        dplyr::select(nctid, reason_for_termination)
  
    ## Return termination reason dataframe
    return(get_why_stopped_df)
    
}
